In [2]:
import numpy as np
from scipy import signal
from scipy import ndimage
from skimage import filters

In [3]:
sobelx = [[-1, 0, 1],
		  [-2, 0, 2],
		  [-1, 0, 1]]
sobelx = np.array(sobelx)
sobelx

array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

In [4]:
sobely = [[-1, -2, -1],
		  [ 0,  0,  0],
		  [ 1,  0,  1]]
sobely = np.array(sobely)
sobely

array([[-1, -2, -1],
       [ 0,  0,  0],
       [ 1,  0,  1]])

In [26]:
shape = (3,16)
size = shape[0]*shape[1]
signal = np.random.randint(100, size=size)
signal

array([89, 42,  7, 40, 69, 80, 98, 41,  5, 37, 37, 93, 21, 77, 42, 50, 65,
       29, 73, 47, 77, 67, 67, 80, 21, 69, 77, 11, 86,  7, 55, 67, 55,  6,
       45, 33, 12, 32,  2, 58, 17,  2, 32, 48, 63, 54, 40, 31])

In [35]:
signal = [0x8d, 0x8d, 0x8e, 0x8f, 0x90, 0x90, 0x91, 0x91, 0x93, 0x93, 0x93, 0x93, 0x93, 0x93, 0x93, 0x93,
          0x94, 0x94, 0x94, 0x94, 0x94, 0x94, 0x94, 0x94, 0x92, 0x92, 0x92, 0x92, 0x92, 0x92, 0x92, 0x92,
          0x90, 0x90, 0x90, 0x8f, 0x8f, 0x8e, 0x8e, 0x8e, 0x8f, 0x8f, 0x8e, 0x8d, 0x8c, 0x8b, 0x8a, 0x8]

In [36]:
signal = np.array(signal)
signal = signal.reshape(shape)
signal

array([[141, 141, 142, 143, 144, 144, 145, 145, 147, 147, 147, 147, 147,
        147, 147, 147],
       [148, 148, 148, 148, 148, 148, 148, 148, 146, 146, 146, 146, 146,
        146, 146, 146],
       [144, 144, 144, 143, 143, 142, 142, 142, 143, 143, 142, 141, 140,
        139, 138,   8]])

In [34]:
result = ndimage.sobel(signal)
# result[result > 255] = 255
# result[result < 0] = 0
result

array([[  0,   6,   8,   1,   2,   6,   6,   3,   0,  -2,  -2,   0,   2,
          1,  -1,   0],
       [  1,   3,  -1,  -6,  -3,   0,   3,   4,   1,  -4,  -4,   0,  -1,
         -3,  -3,  -1],
       [  3,   3,  -7, -11,  -7,  -6,   3,   9,   3,  -2,  -2,   0,  -1,
         -2,  -4,  -3]])

In [30]:
out = [0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
       0x0, 0xb, 0x7, 0x1, 0x4, 0x8, 0xb, 0xd, 0xf, 0x11, 0x14, 0x18, 0x1c, 0x20, 0x23, 0x0, 
       0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x00]

In [31]:
out = np.array(out)
out.reshape(shape)


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  5,  1, 11, 17, 24, 29, 28, 25, 24, 24, 24, 25, 27, 29,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])